# Site settings
baseurl = "https://ndres.me/"
themesDir = "themes"
languageCode = "en-us"
title = "Eliot Andres blog"
theme = "hyde"

DefaultContentLanguage = "en"

# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-105312541-1"
# Disable comments by leaving disqusShortname empty

[params]
	name = "Eliot Andres"
	description = "While the models are training"
	bio = "Freelance machine learning and computer vision engineer. Author of (https://amzn.to/2Znjpht) [More](/about/)"
	# Enter optionally your twitter account
	twitter = ""
	enableRSS = true

	# Integrate Javascript files or stylesheets by adding the url to the external assets or by
	# linking local files with their path relative to the static folder, e.g. "css/styles.css"
	customCSS = []
	customJS  = []

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Navigation links
	home = "While the models are training"
	subscribe = ""
	# Pagination links
	olderPosts = ""
	newerPosts = ""
	readMore = ""
	copyright = "While the models are training: a machine learning blog"
	# Sharing options and author information in posts
	aboutAuthor = "Deep Learning Engineer"
	tweet = ""
	share = ""
	# 404 page
	title404 = "Nothing here"
	subtitle404 = ""

	# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
	iconFont = "mono-social"
    # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
    socialIconStyle = "circle"

# Add additional social link entries underneath
[social]
    twitter  = "https://www.twitter.com/eliotandres"
    githubalt   = "https://www.github.com/eliotandres"

[blackfriday]
  plainIDAnchors = true
  hrefTargetBlank = true
